format = """
[](#9A348E)\
[ ](bg:#9A348E)\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$erlang\
$elixir\
$nodejs\
$python\
$ruby\
$elm\
$golang\
$haskell\
$rust\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)\
\n$status$cmd_duration$character
"""

# Disable the blank line at the start of the prompt
add_newline = true

[status]
format = '[\($symbol$status\)]($style)'
symbol = ''
disabled = false

[character]
success_symbol = '[\$>](bold green)'
error_symbol = '[\$>](bold red)'


# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = false
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:#DA627D fg:#000000"
format = "[ $path ]($style)"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[docker_context]
symbol = " "
style = "bg:#06969A fg:#000000"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#86BBD8 fg:#000000"
#format = '[ $symbol ($version - OTP $otp_version) ]($style)'
format = '[ $symbol]($style)'

[erlang]
style = "bg:#86BBD8 fg:#000000"
format = '[ $symbol($version )]($style)'

[ruby]
style = "bg:#86BBD8 fg:#000000"
format = '[ $symbol($version )]($style)'

[python]
style = "bg:#86BBD8 fg:#000000"
format = '[ $symbol($version )]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D fg:#000000"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D fg:#000000"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#86BBD8 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'

[kubernetes]
symbol = " "
style = "bg:#06969A fg:#000000"
format = '[ $symbol$context/$namespace ]($style)'
disabled = false